### ISSUE TITLE
Hotspot highlighting new empty lines below

### ISSUE THREAD

**Issue by NimG98** [OpenLiberty/openliberty.io#1359]
The last line of code in the `yaml` file is what we want to highlight with the hotspot.
The hotspot does highlight the correct line, but it appears to highlight empty lines below it:

![image](https://user-images.githubusercontent.com/46586499/64449489-08adb700-d0ae-11e9-862e-6bd5dd1bd320.png)

There are no empty lines at the end of the file. But at the end of the file are several nested hotspot tags:
```
    ...
    ...
    # tag::istioRetry[]
    retries:
      # tag::attempts[]
      attempts: 4
      # end::attempts[]
      # tag::retryOn[]
      retryOn: 5xx
      # end::retryOn[]
    # end::istioRetry[]
  # end::route[]
```
