### ISSUE TITLE
Allow guide hotspots to look for exact instead of partial match

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/openliberty.io#1650]
When writing guides and using hotspots, I noticed that the hotspot would also match start and end tags partially. For example, I have a hotspotted `deploy.yaml` file:
```
# tag::system[]
apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: system
  labels:
    name: system
spec:
  # tag::systemImage[]
  applicationImage: guide/system-imagestream:1.0-SNAPSHOT
  # end::systemImage[]
  pullPolicy: Always
  env:
    - name: MP_MESSAGING_CONNECTOR_LIBERTY_KAFKA_BOOTSTRAP_SERVERS
      value: "kafka:9092"
# end::system[]
```

I added a hotspot in the guide that references the whole `system` tag block: `the [hotspot=system file=1]'system' and ...` which I expected to highlight the whole block, however, on the website, it seems that the `# end::systemImage[]` tag is where the highlight ends:

![image](https://user-images.githubusercontent.com/26514093/81838153-c0377a80-9513-11ea-88de-0dffbf268a77.png)

Could the component that highlights the codepane search for an exact match instead of partial to avoid situations like this? If this is too tedious let us know, we can apply a workaround to our hotspot naming convention to avoid edge cases like this.

Thanks!
